import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { pathToFileURL } from "node:url";

const args = Object.fromEntries(process.argv.slice(2).reduce((out, value, i, all) => { if (value.startsWith("--")) out.push([value.slice(2), all[i+1]]); return out; }, []));
for (const key of ["html", "merged", "paper-code", "node-modules", "output-dir"]) if (!args[key]) throw new Error(`missing --${key}`);
const playwrightPath = path.join(args["node-modules"], "playwright", "index.mjs");
const { chromium } = await import(pathToFileURL(playwrightPath).href);
const outputDir = args["output-dir"];
await fs.mkdir(path.join(outputDir, "rows"), { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
const pageErrors = [];
page.on("pageerror", error => pageErrors.push(String(error)));
await page.goto(pathToFileURL(path.resolve(args.html)).href, { waitUntil: "load" });
await page.waitForFunction(() => window.mathReady === true);
const renderError = await page.evaluate(() => window.mathRenderError || "");
const expected = Number(await page.locator("body").getAttribute("data-expected-spans"));
const mathIds = JSON.parse(await page.locator("body").getAttribute("data-math-ids"));
const rendered = await page.locator(".katex").count();
const katexErrors = await page.locator(".katex-error").count();
const visibleText = await page.locator("body").innerText();
const rawDelimiterCount = (visibleText.match(/\$/g) || []).length;
const fullScreenshot = path.join(outputDir, "web_render_preview.png");
await page.screenshot({ path: fullScreenshot, fullPage: true });
for (const qid of mathIds) await page.locator(`section[data-question-id="${qid}"]`).screenshot({ path: path.join(outputDir, "rows", `${qid}.png`) });
await browser.close();
const mergedBytes = await fs.readFile(args.merged);
const errors = [...pageErrors];
if (renderError) errors.push(`render error: ${renderError}`);
if (rendered !== expected) errors.push(`rendered ${rendered} KaTeX nodes; expected ${expected}`);
if (katexErrors) errors.push(`${katexErrors} KaTeX error nodes`);
if (rawDelimiterCount) errors.push(`${rawDelimiterCount} raw dollar delimiters remain visible`);
const manifest = { schema_version:"physics_p1_mcq_web_render_qc_v1", final_status:errors.length?"failed":"passed", paper_code:args["paper-code"], renderer:"KaTeX auto-render", rows:40, rows_with_math:mathIds.length, expected_inline_math_spans:expected, rendered_inline_math_spans:rendered, focused_screenshots:mathIds.length, page_errors:pageErrors.length, katex_errors:katexErrors, raw_delimiter_count:rawDelimiterCount, merged_csv_sha256:crypto.createHash("sha256").update(mergedBytes).digest("hex"), preview_html:path.resolve(args.html), full_screenshot:path.resolve(fullScreenshot), errors };
await fs.writeFile(path.join(outputDir, "qc_manifest.json"), JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify(manifest,null,2));
if (errors.length) process.exitCode = 1;
